[package]
name = "snarkvm-synthesizer"
version = "0.11.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Synthesizer for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "block"
path = "benches/block.rs"
harness = false

[[bench]]
name = "coinbase_puzzle"
path = "benches/coinbase_puzzle.rs"
harness = false
required-features = [ "setup" ]

[[bench]]
name = "transaction"
path = "benches/transaction.rs"
harness = false

[features]
default = [ ]
aleo-cli = [ ]
cuda = [ "snarkvm-algorithms/cuda" ]
rocks = [ "rocksdb" ]
serial = [
  "console/serial",
  "snarkvm-algorithms/serial",
  "snarkvm-curves/serial",
  "snarkvm-fields/serial",
  "snarkvm-utilities/serial"
]
setup = [ ]
timer = [ "aleo-std/timer" ]
wasm = [ ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../circuit"
version = "0.11.1"

[dependencies.console]
package = "snarkvm-console"
path = "../console"
version = "0.11.1"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.11.1"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.11.1"

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.11.1"

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.11.1"
default-features = false

[dependencies.aleo-std]
version = "0.1.15"
default-features = false

[dependencies.anyhow]
version = "1.0.71"

[dependencies.bincode]
version = "1"

[dependencies.blake2]
version = "0.10"
default-features = false

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "1.9"
features = [ "serde", "rayon" ]

[dependencies.itertools]
version = "0.10.1"

[dependencies.once_cell]
version = "1.17"

[dependencies.parking_lot]
version = "0.12"

[dependencies.paste]
version = "1.0.12"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"

[dependencies.rocksdb]
version = "0.21"
default-features = false
features = [ "lz4" ]
optional = true

[dependencies.serde]
version = "1.0"

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dependencies.tracing]
version = "0.1"

[dependencies.ureq]
version = "2.6.2"
features = [ "json" ]

[dev-dependencies.console]
package = "snarkvm-console"
path = "../console"
features = [ "test" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.criterion]
version = "0.4.0"

[dev-dependencies.serial_test]
version = "2"

[dev-dependencies.tempfile]
version = "3.4"

[dev-dependencies.tracing-test]
version = "0.2"
